"""empty message

Revision ID: 020416fc92f4
Revises: 71b53a443a04
Create Date: 2022-11-16 00:08:30.775443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020416fc92f4'
down_revision = '71b53a443a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'image_file',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'image_file',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
