"""empty message

Revision ID: 552d96b4b170
Revises: d9f4f4827441
Create Date: 2022-11-18 20:36:31.616552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552d96b4b170'
down_revision = 'd9f4f4827441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_gym',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gym_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gym.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('gym', sa.Column('name', sa.String(length=30), nullable=True))
    op.alter_column('gym', 'gym_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.create_unique_constraint(None, 'gym', ['name'])
    op.add_column('posting', sa.Column('title', sa.String(length=80), nullable=False))
    op.add_column('posting', sa.Column('date_posted', sa.DateTime(), nullable=False))
    op.alter_column('posting', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.alter_column('posting', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posting', 'date_posted')
    op.drop_column('posting', 'title')
    op.drop_constraint(None, 'gym', type_='unique')
    op.alter_column('gym', 'gym_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('gym', 'name')
    op.drop_table('user_gym')
    # ### end Alembic commands ###
