"""empty message

Revision ID: 71b53a443a04
Revises: d9f4f4827441
Create Date: 2022-11-15 23:59:04.139486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b53a443a04'
down_revision = 'd9f4f4827441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posting', sa.Column('title', sa.String(length=80), nullable=False))
    op.add_column('posting', sa.Column('date_posted', sa.DateTime(), nullable=False))
    op.alter_column('posting', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.alter_column('posting', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posting', 'date_posted')
    op.drop_column('posting', 'title')
    # ### end Alembic commands ###
